# Your project's server will run on localhost:xxxx at this port
PORT: 8000
BROWSERSLIST_CONFIG: ".browserslistrc"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets
  assets:
    - "src/assets/js/{custom,vendor}/*.js"
    - "src/assets/ss/**/*.css"
    - "src/pages/**/images/**/*"
    - "src/pages/**/**/images/*" 
    - "src/pages/**/files/**/*" 
  # Paths to Foundation sccs libraries
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules if you desire
  entries:
    - "src/assets/js/foundation-pack.js"
  # Paths to JavaScript to bundle and load in addition to the webpack list
  javascriptpack:
    - "src/assets/js/app-pack.js"
    - "src/assets/js/shareWidget.js"
  # Paths to JavaScript to bundle and load if using prebuilt Foundation instead of webpack
  javascript:
    - "src/assets/js/foundation-prebuilt.js"
    - "src/assets/js/app.js"
    - "src/assets/js/shareWidget.js"
